// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const updateCompletedAt = `-- name: UpdateCompletedAt :batchexec
UPDATE learning_items
SET completed_at = NOW()
WHERE id = $1
`

type UpdateCompletedAtBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) UpdateCompletedAt(ctx context.Context, id []string) *UpdateCompletedAtBatchResults {
	batch := &pgx.Batch{}
	for _, a := range id {
		vals := []interface{}{
			a,
		}
		batch.Queue(updateCompletedAt, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpdateCompletedAtBatchResults{br, len(id), false}
}

func (b *UpdateCompletedAtBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpdateCompletedAtBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
