// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: flash_cards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLearningItemsByTopicAndCompleted = `-- name: GetLearningItemsByTopicAndCompleted :many
SELECT id, image_link, english_word, vietnamese_word, english_sentences, created_at, updated_at, completed_at, deleted_at, user_id, topic_id FROM learning_items 
WHERE topic_id = $1 AND deleted_at IS NULL
ORDER BY completed_at ASC
LIMIT $2
`

type GetLearningItemsByTopicAndCompletedParams struct {
	TopicID pgtype.Text `json:"topic_id"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) GetLearningItemsByTopicAndCompleted(ctx context.Context, arg GetLearningItemsByTopicAndCompletedParams) ([]LearningItem, error) {
	rows, err := q.db.Query(ctx, getLearningItemsByTopicAndCompleted, arg.TopicID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningItem{}
	for rows.Next() {
		var i LearningItem
		if err := rows.Scan(
			&i.ID,
			&i.ImageLink,
			&i.EnglishWord,
			&i.VietnameseWord,
			&i.EnglishSentences,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.UserID,
			&i.TopicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
