// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: learning_item.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const createLearningItem = `-- name: CreateLearningItem :one
INSERT INTO learning_item (
    id,
    image_link,
    english_word,
    vietnamese_word,
    english_sentences
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, image_link, english_word, vietnamese_word, english_sentences
`

type CreateLearningItemParams struct {
	ID               string   `json:"id"`
	ImageLink        string   `json:"image_link"`
	EnglishWord      string   `json:"english_word"`
	VietnameseWord   string   `json:"vietnamese_word"`
	EnglishSentences []string `json:"english_sentences"`
}

func (q *Queries) CreateLearningItem(ctx context.Context, arg CreateLearningItemParams) (LearningItem, error) {
	row := q.db.QueryRowContext(ctx, createLearningItem,
		arg.ID,
		arg.ImageLink,
		arg.EnglishWord,
		arg.VietnameseWord,
		pq.Array(arg.EnglishSentences),
	)
	var i LearningItem
	err := row.Scan(
		&i.ID,
		&i.ImageLink,
		&i.EnglishWord,
		&i.VietnameseWord,
		pq.Array(&i.EnglishSentences),
	)
	return i, err
}

const deleteLearningItem = `-- name: DeleteLearningItem :one
DELETE FROM learning_item WHERE id = $1 RETURNING id, image_link, english_word, vietnamese_word, english_sentences
`

func (q *Queries) DeleteLearningItem(ctx context.Context, id string) (LearningItem, error) {
	row := q.db.QueryRowContext(ctx, deleteLearningItem, id)
	var i LearningItem
	err := row.Scan(
		&i.ID,
		&i.ImageLink,
		&i.EnglishWord,
		&i.VietnameseWord,
		pq.Array(&i.EnglishSentences),
	)
	return i, err
}

const getLearningItem = `-- name: GetLearningItem :many
SELECT id, image_link, english_word, vietnamese_word, english_sentences FROM learning_item
`

func (q *Queries) GetLearningItem(ctx context.Context) ([]LearningItem, error) {
	rows, err := q.db.QueryContext(ctx, getLearningItem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningItem{}
	for rows.Next() {
		var i LearningItem
		if err := rows.Scan(
			&i.ID,
			&i.ImageLink,
			&i.EnglishWord,
			&i.VietnameseWord,
			pq.Array(&i.EnglishSentences),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
