// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LearningItem struct {
	ID               string             `json:"id"`
	ImageLink        string             `json:"image_link"`
	EnglishWord      string             `json:"english_word"`
	VietnameseWord   pgtype.Text        `json:"vietnamese_word"`
	EnglishSentences []string           `json:"english_sentences"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	UserID           pgtype.Text        `json:"user_id"`
	TopicID          pgtype.Text        `json:"topic_id"`
}

type Test struct {
	TestID string `json:"test_id"`
}

type Topic struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID                string             `json:"id"`
	FirstName         string             `json:"first_name"`
	LastName          string             `json:"last_name"`
	Email             string             `json:"email"`
	EncryptedPassword string             `json:"encrypted_password"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}
