// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
)

type Querier interface {
	CreateLearningItem(ctx context.Context, arg CreateLearningItemParams) (LearningItem, error)
	CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error)
	DeleteLearningItem(ctx context.Context, id string) (LearningItem, error)
	DeleteTopic(ctx context.Context, id string) (Topic, error)
	GetAllLearningItems(ctx context.Context) ([]LearningItem, error)
	GetAllTopics(ctx context.Context) ([]GetAllTopicsRow, error)
	GetLearningItemById(ctx context.Context, id string) (LearningItem, error)
	GetLearningItemsByTopicAndCompleted(ctx context.Context, arg GetLearningItemsByTopicAndCompletedParams) ([]LearningItem, error)
	GetTopicsAndTotalLearningItems(ctx context.Context) ([]GetTopicsAndTotalLearningItemsRow, error)
	HardDeleteLearningItem(ctx context.Context, id string) (LearningItem, error)
	UpdateLearningItem(ctx context.Context, arg UpdateLearningItemParams) error
}

var _ Querier = (*Queries)(nil)
