// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: topics.sql

package db

import (
	"context"
)

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (
    id,
    name,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    now(),
    now()
) RETURNING id, name, created_at, updated_at, deleted_at
`

type CreateTopicParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic, arg.ID, arg.Name)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTopic = `-- name: DeleteTopic :one
UPDATE topics SET deleted_at = now() WHERE id = $1 RETURNING id, name, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteTopic(ctx context.Context, id string) (Topic, error) {
	row := q.db.QueryRow(ctx, deleteTopic, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllTopics = `-- name: GetAllTopics :many
SELECT id, name FROM topics 
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

type GetAllTopicsRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetAllTopics(ctx context.Context) ([]GetAllTopicsRow, error) {
	rows, err := q.db.Query(ctx, getAllTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllTopicsRow{}
	for rows.Next() {
		var i GetAllTopicsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopicsAndTotalLearningItems = `-- name: GetTopicsAndTotalLearningItems :many
SELECT t.id, t.name, COUNT(li.id) AS total_learning_items
FROM topics t LEFT JOIN learning_items li ON t.id = li.topic_id
WHERE t.deleted_at IS NULL AND li.deleted_at IS NULL
GROUP BY t.id
ORDER BY t.created_at DESC
`

type GetTopicsAndTotalLearningItemsRow struct {
	ID                 string `json:"id"`
	Name               string `json:"name"`
	TotalLearningItems int64  `json:"total_learning_items"`
}

func (q *Queries) GetTopicsAndTotalLearningItems(ctx context.Context) ([]GetTopicsAndTotalLearningItemsRow, error) {
	rows, err := q.db.Query(ctx, getTopicsAndTotalLearningItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopicsAndTotalLearningItemsRow{}
	for rows.Next() {
		var i GetTopicsAndTotalLearningItemsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.TotalLearningItems); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
